### ISSUE TITLE
4 tests failed; 6 uncaught exceptions from yarn test

### ISSUE THREAD

**Issue by dckc** [lari-labs/dapp-ertp-airdrop#46]
Should I expect `yarn test` to work?

I get:

```
  4 tests failed
  2 tests todo
  1 unhandled rejection
  6 uncaught exceptions
```

full details are in [yarn-test.md](https://gist.github.com/dckc/c33642d57398f7ac10d6dd48dee798df#file-yarn-test-md)

Which tests should I look at for current work?

**Comment by dckc** [comment]
this one passes...

```
$ yarn test test/airdropZone/test-airdrop.js
yarn run v1.22.21
$ ava --verbose test/airdropZone/test-airdrop.js

  ✔ zoe - ownable-Airdrop contract
    ℹ ------------ testing claim capabilities -------
    ℹ -----------------------------------------
    ℹ AirdropResult Object @Alleged: ZoeSeatKit userSeat {}
    ℹ -----------------------------------------
    ℹ expectedPayout value {
        brand: Object @Alleged: memes brand {},
        value: 11000n,
      }
    ℹ -----------------------------------------
    ℹ ------------ testing claim capabilities -------
    ℹ -----------------------------------------
    ℹ AirdropResult Object @Alleged: ZoeSeatKit userSeat {}
    ℹ -----------------------------------------
    ℹ expectedPayout value {
        brand: Object @Alleged: memes brand {},
        value: 7000n,
      }
    ℹ -----------------------------------------
    ℹ inside test utilities
    ℹ ------------ testing claim capabilities -------
    ℹ -----------------------------------------
    ℹ AirdropResult Object @Alleged: ZoeSeatKit userSeat {}
    ℹ -----------------------------------------
    ℹ expectedPayout value {
        brand: Object @Alleged: memes brand {},
        value: 4000n,
      }
    ℹ -----------------------------------------
  ─

  1 test passed
Done in 3.48s.
```

**Comment by dckc** [comment]
I just tried `yarn test test/airdropZone/test-airdrop.js` again today (cf50af1) and it fails:

<details><summary>yarn test log</summary>

```
$ yarn test test/airdropZone/test-airdrop.js
yarn run v1.22.21
$ ava --verbose test/airdropZone/test-airdrop.js

  - [todo] Airdrop Claim before contract status has been marked as open
REJECTED from ava test.beforeEach(): (Error#1)
Nested error under Error#1
  ✘ [fail]: beforeEach hook for PurseHolder Rejected promise returned by test
  ✘ [fail]: beforeEach hook for Outdated Airdrop campaign approach Rejected promise returned by test
Error#1: customTerms: {"basePayoutQuantity":{"brand":"[Alleged: memes brand]","value":"[1000n]"},"endTime":{"relValue":"[1000000n]","timerBrand":"[Alleged: timerBrand]"},"startTime":{"relValue":"[604800000n]","timerBrand":"[Seen]"}} - Must have missing properties ["rootHash"]
  at throwLabeled (.../patterns/src/utils.js:130:23)
  at applyLabelingError (.../patterns/src/utils.js:154:1)
  at checkMatches (.../patterns/src/patterns/patternMatchers.js:375:1)
  at mustMatch (.../patterns/src/patterns/patternMatchers.js:528:1)
  at Alleged: zcf.getTerms (.../zoe/src/contractFacet/zcfZygote.js:305:1)
  at start (.../agoric-basics-contract/src/airdrop/prepare.js:101:5)
  at Object.startContract (.../zoe/src/contractFacet/zcfZygote.js:382:1)

Error#1 ERROR_NOTE: Caused by (Error#2)
  Error#2: {
    basePayoutQuantity: { brand: Object [Alleged: memes brand] {}, value: 1000n },
    startTime: { timerBrand: Object [Alleged: timerBrand] {}, relValue: 604800000n },
    endTime: { timerBrand: Object [Alleged: timerBrand] {}, relValue: 1000000n }
  } - Must have missing properties [ 'rootHash' ]
    at assertChecker (.../pass-style/src/passStyle-helpers.js:75:1)
    at checkMatchesInternal (.../patterns/src/patterns/patternMatchers.js:452:8)
    at applyLabelingError (.../patterns/src/utils.js:152:8)
    at checkMatches (.../patterns/src/patterns/patternMatchers.js:375:1)
    at mustMatch (.../patterns/src/patterns/patternMatchers.js:528:1)
    at Alleged: zcf.getTerms (.../zoe/src/contractFacet/zcfZygote.js:305:1)
    at start (.../agoric-basics-contract/src/airdrop/prepare.js:101:5)
    at Object.startContract (.../zoe/src/contractFacet/zcfZygote.js:382:1)
  
REJECTED from ava test.beforeEach(): (Error#3)
Error#3: customTerms: {"basePayoutQuantity":{"brand":"[Alleged: memes brand]","value":"[1000n]"},"endTime":{"relValue":"[1000000n]","timerBrand":"[Alleged: timerBrand]"},"startTime":{"relValue":"[604800000n]","timerBrand":"[Seen]"}} - Must have missing properties ["rootHash"]
  at throwLabeled (.../patterns/src/utils.js:130:23)
  at applyLabelingError (.../patterns/src/utils.js:154:1)
  at checkMatches (.../patterns/src/patterns/patternMatchers.js:375:1)
  at mustMatch (.../patterns/src/patterns/patternMatchers.js:528:1)
  at Alleged: zcf.getTerms (.../zoe/src/contractFacet/zcfZygote.js:305:1)
  at start (.../agoric-basics-contract/src/airdrop/prepare.js:101:5)
  at Object.startContract (.../zoe/src/contractFacet/zcfZygote.js:382:1)

Error#3 ERROR_NOTE: Caused by (Error#4)
  Error#4: {
    basePayoutQuantity: { brand: Object [Alleged: memes brand] {}, value: 1000n },
    startTime: { timerBrand: Object [Alleged: timerBrand] {}, relValue: 604800000n },
    endTime: { timerBrand: Object [Alleged: timerBrand] {}, relValue: 1000000n }
  } - Must have missing properties [ 'rootHash' ]
    at assertChecker (.../pass-style/src/passStyle-helpers.js:75:1)
    at checkMatchesInternal (.../patterns/src/patterns/patternMatchers.js:452:8)
    at applyLabelingError (.../patterns/src/utils.js:152:8)
    at checkMatches (.../patterns/src/patterns/patternMatchers.js:375:1)
    at mustMatch (.../patterns/src/patterns/patternMatchers.js:528:1)
    at Alleged: zcf.getTerms (.../zoe/src/contractFacet/zcfZygote.js:305:1)
    at start (.../agoric-basics-contract/src/airdrop/prepare.js:101:5)
    at Object.startContract (.../zoe/src/contractFacet/zcfZygote.js:382:1)
  
Nested error under Error#3
  ✘ 2 tests remaining in test/airdropZone/test-airdrop.js
  ─

  beforeEach hook for PurseHolder

  Rejected promise returned by test. Reason:

  Error {
    message: 'customTerms: {"basePayoutQuantity":{"brand":"[Alleged: memes brand]","value":"[1000n]"},"endTime":{"relValue":"[1000000n]","timerBrand":"[Alleged: timerBrand]"},"startTime":{"relValue":"[604800000n]","timerBrand":"[Seen]"}} - Must have missing properties ["rootHash"]',
  }

  › throwLabeled (.../patterns/src/utils.js:130:23)
  › applyLabelingError (.../patterns/src/utils.js:154:1)
  › checkMatches (.../patterns/src/patterns/patternMatchers.js:375:1)
  › mustMatch (.../patterns/src/patterns/patternMatchers.js:528:1)
  › Alleged: zcf.getTerms (.../zoe/src/contractFacet/zcfZygote.js:305:1)
  › start (.../agoric-basics-contract/src/airdrop/prepare.js:101:5)
  › Object.startContract (.../zoe/src/contractFacet/zcfZygote.js:382:1)



  beforeEach hook for Outdated Airdrop campaign approach

  Rejected promise returned by test. Reason:

  Error {
    message: 'customTerms: {"basePayoutQuantity":{"brand":"[Alleged: memes brand]","value":"[1000n]"},"endTime":{"relValue":"[1000000n]","timerBrand":"[Alleged: timerBrand]"},"startTime":{"relValue":"[604800000n]","timerBrand":"[Seen]"}} - Must have missing properties ["rootHash"]',
  }

  › throwLabeled (.../patterns/src/utils.js:130:23)
  › applyLabelingError (.../patterns/src/utils.js:154:1)
  › checkMatches (.../patterns/src/patterns/patternMatchers.js:375:1)
  › mustMatch (.../patterns/src/patterns/patternMatchers.js:528:1)
  › Alleged: zcf.getTerms (.../zoe/src/contractFacet/zcfZygote.js:305:1)
  › start (.../agoric-basics-contract/src/airdrop/prepare.js:101:5)
  › Object.startContract (.../zoe/src/contractFacet/zcfZygote.js:382:1)

  ─

  2 hooks failed
  1 test todo
error Command failed with exit code 1.
```
</details>

**Comment by dckc** [comment]
This is fixed, as we discussed:
https://github.com/hindley-milner-systems/dapp-ertp-airdrop/pull/68#issuecomment-2145872680
